#!/usr/bin/env node
/**
 * Bump TranscriptPRO version in all three sources of truth and sync Cargo.lock.
 *
 *   npm run bump 0.1.4          # stable
 *   npm run bump 0.1.4-rc.1     # prerelease (workflow flags it as prerelease)
 *
 * Touches:
 *   - package.json                 (frontend)
 *   - src-tauri/tauri.conf.json    (bundler + updater)
 *   - src-tauri/Cargo.toml         (Rust crate)
 *   - src-tauri/Cargo.lock         (regenerated by `cargo update -p transcript-pro`)
 *
 * Uses regex-based string substitution instead of JSON.parse/stringify so the
 * original formatting (indentation, key order, compact arrays) is preserved —
 * keeps diffs minimal and review-friendly.
 *
 * Does NOT commit or tag — that's intentional. The release procedure requires
 * a local universal-apple-darwin build and a CHANGELOG.md edit between bump
 * and tag.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SEMVER = /^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/;

function fail(msg) {
  console.error(`✗ ${msg}`);
  process.exit(1);
}

/**
 * Replace `pattern` in the file at `path` using `replacer`. Detects whether
 * the regex actually matched (independently of whether the content changed —
 * matters when bumping to the current version for a dry-run check).
 */
function patchFile(path, pattern, replacer, label) {
  const original = readFileSync(path, "utf8");
  let matched = false;
  const updated = original.replace(pattern, (...args) => {
    matched = true;
    return replacer(...args);
  });
  if (!matched) fail(`Couldn't locate version field in ${label} (regex: ${pattern})`);
  writeFileSync(path, updated);
}

const newVersion = process.argv[2];
if (!newVersion) fail("Usage: npm run bump <version>   (e.g. 0.1.4 or 0.1.4-rc.1)");
if (!SEMVER.test(newVersion)) fail(`"${newVersion}" is not a valid semver`);

const oldVersion = JSON.parse(readFileSync(resolve(ROOT, "package.json"), "utf8")).version;

// 1. package.json — top-level "version": "..." appears once
patchFile(
  resolve(ROOT, "package.json"),
  /("version"\s*:\s*)"[^"]+"/,
  (_, prefix) => `${prefix}"${newVersion}"`,
  "package.json",
);
console.log(`  package.json              ${oldVersion} → ${newVersion}`);

// 2. tauri.conf.json — top-level "version" sits right under productName, before
// "identifier"; targeting the first "version" key is safe.
patchFile(
  resolve(ROOT, "src-tauri/tauri.conf.json"),
  /("version"\s*:\s*)"[^"]+"/,
  (_, prefix) => `${prefix}"${newVersion}"`,
  "src-tauri/tauri.conf.json",
);
console.log(`  src-tauri/tauri.conf.json ${oldVersion} → ${newVersion}`);

// 3. Cargo.toml — package version sits inside [package] table at line 3.
// The regex anchors to start-of-line and matches `version = "..."` exactly so
// it can't be confused by build-deps that also have `version =` inside table
// literals (those don't start a line).
patchFile(
  resolve(ROOT, "src-tauri/Cargo.toml"),
  /^(\s*version\s*=\s*)"[^"]+"/m,
  (_, prefix) => `${prefix}"${newVersion}"`,
  "src-tauri/Cargo.toml",
);
console.log(`  src-tauri/Cargo.toml      ${oldVersion} → ${newVersion}`);

// 4. Cargo.lock — `cargo update -p transcript-pro` syncs the lock without
// re-resolving the entire graph or recompiling.
try {
  execSync("cargo update -p transcript-pro", {
    cwd: resolve(ROOT, "src-tauri"),
    stdio: ["ignore", "ignore", "inherit"],
  });
  console.log(`  src-tauri/Cargo.lock      synced`);
} catch {
  console.warn("  ⚠ Cargo.lock not auto-synced — run `cargo check` in src-tauri before committing");
}

console.log();
console.log("✓ Bumped to", newVersion);
console.log();
console.log("Next (release procedure — see MEMORY/feedback_release_procedure):");
console.log("  1. Update CHANGELOG.md — add ## [" + newVersion + "] section above prior entries");
console.log("  2. npm run build && npm run tauri build -- --target universal-apple-darwin");
console.log("  3. git commit -am \"Release v" + newVersion + "\"  && push, open PR, wait for green CI, merge");
console.log("  4. git tag -a v" + newVersion + " -m \"Release v" + newVersion + "\" && git push origin v" + newVersion);
